name: Build and Push Docker DevContainer Image to GitHub Container Registry

on:
  workflow_run:
    workflows: ["Run Build Check"]  # Name of the workflow to wait for
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the test workflow passed

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/umlcloudcomputing/photosky-devcontainer:latest -f .devcontainer/Dockerfile .

      # Step 3: Log in to GitHub Container Registry (only for pushes)
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 4: Push the Docker image to GitHub Container Registry (only for pushes)
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/umlcloudcomputing/photosky-devcontainer:latest
