name: Build and Push Docker DevContainer Image to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'  # Only trigger on changes to files in .devcontainer
  pull_request:
    branches:
      - main
    paths:
      - '.devcontainer/**'  # Only trigger on changes to files in .devcontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/umlcloudcomputing/photosky-devcontainer:latest -f .devcontainer/Dockerfile .

      # Step 3: Log in to GitHub Container Registry (only for pushes)
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 4: Push the Docker image to GitHub Container Registry (only for pushes)
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/umlcloudcomputing/photosky-devcontainer:latest
