name: 'Prebuild Dev Container Image'

on:
  # Trigger the workflow on changes to the main branch and on pull requests to main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds and caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Pre-build and publish the devcontainer image
      - name: Build and push Dev Container image
        uses: devcontainers/ci@v0.3
        with:
          # The full name of the image, including the registry and repo
          imageName: ghcr.io/uMLCloudComputing/photosky-devcontainer
          # Optionally, reuse cached layers from the existing image
          cacheFrom: ghcr.io/uMLCloudComputing/photosky-devcontainer
          # Always push the image to the container registry
          push: always
